# Generated by Django 4.0.1 on 2022-01-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=50)),
                ('expected_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=50)),
                ('names', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myquizapi.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myquizapi.student')),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('quiz_descripion', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myquizapi.question')),
            ],
        ),
    ]
