# Generated by Django 4.0.1 on 2022-01-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myquizapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_descripion',
            new_name='quiz_description',
        ),
    ]
