# Generated by Django 4.0.1 on 2022-01-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myquizapi', '0002_rename_quiz_descripion_quiz_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myquizapi.question'),
        ),
    ]
