# Generated by Django 4.0.1 on 2022-01-27 08:38

from django.db import migrations, models
import myquizapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myquizapi', '0005_alter_result_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(default=[myquizapi.models.question], max_length=100),
        ),
    ]
