# Generated by Django 4.0.1 on 2022-01-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquizapi', '0006_alter_quiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quest_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_id',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(default=[models.CharField(max_length=100)], max_length=100),
        ),
    ]
