# Generated by Django 4.0.1 on 2022-02-02 08:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myquizapi', '0009_alter_quiz_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_title',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='question',
            new_name='ikibazo',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='result',
            name='student',
        ),
        migrations.AddField(
            model_name='quiz',
            name='choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('i', 'my_choices'), ('u', 'my_choices')], default=(('i', 'my_choices'), ('u', 'my_choices')), max_length=3),
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
